### PR TITLE
Currently using the existing details on update

### PR DESCRIPTION
**Pull request by kehundley-fadv**
I think I have found an issue with the current script. At first I thought the update code didn't work, but then I discovered that if I force it to run twice the second time would work as expected.

Looking at the code it apprears it picking up the details from the previous version instead of getting the new details from the new version.

### CODE REVIEW

**Comment by ab77** [comment]
I've had a look and the CFN update request contains both a `ResourceProperties` and an `OldResourceProperties`. So what you are saying, there is never a need to use data under the `Old` key?

**Comment by kehundley-fadv** [comment]
In this case I wouldn't think you would want to use the `OldResourceProperties` as it doesn't contain the current details.

For example, I updated the Lambda Role to allow management of the Cognito Resource Servers as this is not available through the standard CloudFormation resource types. Everything worked as expected except when I tried add new Scopes. The update completed, but the current configuration wasn't applied. 

CFT when stack was Created:
```yaml
  ResourceServer
    Type: 'Custom::CognitoResourceServer'
    Properties:
      ServiceToken: !Sub '${CustomResourceLambdaArn}'
      AgentService: cognito-idp
      AgentType: client
      AgentCreateMethod: create_resource_server
      AgentUpdateMethod: update_resource_server
      AgentDeleteMethod: delete_resource_server
      AgentResourceId: Identifier
      AgentCreateArgs:
        UserPoolId: !Ref UserPoolId
        Name: !Ref ClientName
        Identifier: !Ref ClientName
      AgentUpdateArgs:
        UserPoolId: !Ref UserPoolId
        Name: !Ref ClientName
        Identifier: !Ref ClientName
      AgentDeleteArgs:
        UserPoolId: !Ref UserPoolId
        Identifier: !Ref ClientName
```
CFT Update (Scopes added):
```yaml
  ResourceServer:
    Type: 'Custom::CognitoResourceServer'
    Properties:
      ServiceToken: !Sub '${CustomResourceLambdaArn}'
      AgentService: cognito-idp
      AgentType: client
      AgentCreateMethod: create_resource_server
      AgentUpdateMethod: update_resource_server
      AgentDeleteMethod: delete_resource_server
      AgentResourceId: Identifier
      AgentCreateArgs:
        UserPoolId: !Ref UserPoolId
        Name: !Ref ClientName
        Identifier: !Ref ClientName
        Scopes:
          - ScopeName: all
            ScopeDescription: All Access
      AgentUpdateArgs:
        UserPoolId: !Ref UserPoolId
        Name: !Ref ClientName
        Identifier: !Ref ClientName
        Scopes:
          - ScopeName: all
            ScopeDescription: All Access
      AgentDeleteArgs:
        UserPoolId: !Ref UserPoolId
        Identifier: !Ref ClientName
```
I noticed that if I forced the it to run a second time then it would correctly apply the desired changes. From looking at the code (I'm no expert on Python) I believe what is happening is that it's picking the old configuration from `OldResourceProperties` which does not have my scope changes, instead of using `ResourceProperties` which does. When I force it to run the second time it `OldResourceProperties` contains the scope updates and those updates are applied to the resource.

Make sense?

**Comment by ab77** [comment]
Yep, I can't think of a use case where `OldResourceProperties` will be used. Thank you.

**Comment by kehundley-fadv** [comment]
@ab77
Btw, I can confirm that this project works with the Cognito Resource Servers if you want to add it to the Lambda Role
`- 'cognito-idp:*ResourceServer'`

**Comment by ab77** [comment]
Please feel free to add a sensible (generic) resource server to the example stack and submit another PR.

**Comment by kehundley-fadv** [comment]
I'll create a PR for this.

Could you help me with one more bug? I'm having trouble with the `UserPoolClient` example. I've tried to figure out the right way to resolve it, but I'm having trouble pinpointing the right way to fix it. Sorry for posting this here, but you don't have Issues enabled on the project.

Here is the issue. When calling `UserPoolClient` you do not supply ClientId, and it's returned in the response from the API call. However, the call to `update_user_pool_client` requires the ClientId to be provided. I've supplied `AgentResourceId: ClientId` as in the example, but when the update call is made to the API it's placing the `PhysicalResourceId` as the value for the ClientId which isn't correct.

I think the issue is that ClientId is nested under `UserPoolClient` in the create response and not at the root.
```json
response = {"UserPoolClient":{"ClientId":"abc123"}}
```

CFT snippet:
```yaml
  UserPoolClient:
    Type: 'Custom::CognitoUserPoolClient'
    Properties:
      ServiceToken: !Sub '${CustomResourceLambdaArn}'
      AgentService: cognito-idp
      AgentType: client
      AgentCreateMethod: create_user_pool_client
      AgentUpdateMethod: update_user_pool_client
      AgentDeleteMethod: delete_user_pool_client
      AgentResourceId: ClientId
      AgentCreateArgs: !Sub |
        {
          "UserPoolId": "${UserPoolId}",
          "ClientName": "${ClientName}",
          "GenerateSecret": true,
          "AllowedOAuthFlows": [
            "client_credentials"
          ],
          "AllowedOAuthScopes": [
            "redacted"
          ],
          "AllowedOAuthFlowsUserPoolClient": true
        }
      AgentUpdateArgs: !Sub |
        {
          "UserPoolId": "${UserPoolId}",
          "ClientName": "${ClientName}",
          "AllowedOAuthFlows": [
            "client_credentials"
          ],
          "AllowedOAuthScopes": [
            "redacted"
          ],
          "AllowedOAuthFlowsUserPoolClient": true
        }
      AgentDeleteArgs:
        UserPoolId: !Ref UserPoolId
```
CloudWatch log for the update call:
```
agent_method=update_user_pool_client, agent_kwargs={'ClientId': 'f0e097e4-79fd-4f9d-9382-ec8e50db3c45', 'UserPoolId': 'redacted', 'ClientName': 'redacted', 'AllowedOAuthFlows': ['client_credentials'], 'AllowedOAuthScopes': ['redacted'], 'AllowedOAuthFlowsUserPoolClient': True}
```

I've confirmed that `f0e097e4-79fd-4f9d-9382-ec8e50db3c45` matches the `PhysicalResourceId` and is not the `ClientId` returned by the create call.

Any help with this is much appreciated.

**Comment by kehundley-fadv** [comment]
I was able to figure out how to get the correct value into the ClientId

I had to add `AgentWaitQueryExpr: '$.UserPoolClient.ClientId'` to the example. I can add this to the PR as well

**Comment by ab77** [comment]
Good idea to add `AgentWaitQueryExpr: '$.UserPoolClient.ClientId'` to the example template, please feel free to submit a separate PR with this change.

**Pull request merged**
